
export const INITIAL_MODEL_CLAUSES: Record<string, string> = {
  'Data Ownership': "Customer retains all rights, title, and interest in and to all data, information, and content provided by Customer ('Customer Inputs'). The service provider acquires no rights in Customer Inputs, other than the right to host and use the Customer Inputs solely as necessary to provide the AI services. All outputs generated by the AI services for the Customer ('Outputs') are the sole and exclusive property of the Customer.",
  'Data Storage & Processing': "All Customer Inputs and Outputs will be stored and processed exclusively within the European Union (EU) or a jurisdiction with an adequate data protection decision from the European Commission. Data will be encrypted both in transit and at rest using industry-standard cryptographic protocols.",
  'Model Training': "The service provider is strictly prohibited from using any Customer Inputs or Outputs for the purpose of training, retraining, or improving any of its artificial intelligence models, algorithms, or related technologies, either for its own benefit or for the benefit of any third party.",
};
